version: '3'

services:
  server:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/loja-virtual
      - ./nginx:/etc/nginx/conf.d
    links:
      - php
    networks:
      - internal

  php:
    image: php:8.3.2-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html/loja-virtual
    networks:
      - internal

networks:
  internal:
    driver: bridge